spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: redis2019
    timeout: 3000 # 连接超时时间（毫秒）
    lettuce: #springboot2.x redis客户端从jedis换成lettuce(可伸缩线程安全)
      pool:
        max-active: 200 # # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -
        max-idle: 10 # 连接池中的最大空闲连接 默认 8
        min-idle: 0  # 连接池中的最小空闲连接 默认 0
    # Redis expireTime
    expire:
      default: 864000
      token: 25920000
